version: '3.8'

services:
  backend:
    build: . # Tells Docker to look in the current folder for the Dockerfile
    container_name: topsec_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/topsec?schema=public"
      PORT: 3000
      FRONTEND_URL: "http://localhost:3001"
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-db.sh", "db:5432", "--", "npm", "run", "start:dev"]

  db:
    image: postgres:16-alpine
    container_name: topsec_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: topsec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: